### ISSUE TITLE
Missing NeRF and NeuralImageFunction class in the src.

### ISSUE THREAD

**Issue by JeanDiable** [qimaqi/Implicit-Zoo#1]
`from src.model_zoo.neuralimage import NeuralImageFunction
from src.model_zoo.siren import INR, Sine, Siren
from src.model_zoo.vgg_simplified import Vgg
from src.model_zoo.semantic_nerf import Semantic_NeRF`

Hi there, I want to use your dataset but missing some important codes. When will you upload them? Thanks a lot.

**Comment by qimaqi** [comment]
Thanks for your interests, I comment these package and I will release the code later after paper decision comes out!

You can find detailed usage in notebook
